In [1]:
# PART 1: Import libraries and check dataset path

import pandas as pd
import os

file_path = "../data/raw/EV data by country 2026.xlsx"

print("File exists:",os.path.exists(file_path))

File exists: True

In [3]:
# PART 2: Load the EV dataset

df = pd.read_excel(file_path,sheet_name="GEVO_EV_2026")

print("Dataset loaded successfully")
print("Rows:",df.shape[0])
print("Columns:",df.shape[1])
df.head()

Dataset loaded successfully
Rows: 49375
Columns: 9

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
0,Chile,Historical,EV charging points,EVSE,Publicly available fast,2011,charging points,1.0,Other
1,Norway,Historical,EV charging points,EVSE,Publicly available fast,2011,charging points,18.0,Other
2,Portugal,Historical,EV charging points,EVSE,Publicly available fast,2011,charging points,6.0,Other
3,Canada,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,2.0,Other
4,Chile,Historical,EV charging points,EVSE,Publicly available fast,2012,charging points,4.0,Other

In [7]:
# PART 5: Check column names

print(df.columns.tolist())

['region_country', 'category', 'parameter', 'mode', 'powertrain', 'year', 'unit', 'value', 'Aggregate group']

In [6]:
# PART 6: Check missing values

missing_values = df.isnull().sum()

print(missing_values)

# PART 7: Check duplicate rows

print("Duplicate rows:",df.duplicated().sum())

region_country      1078
category               0
parameter              0
mode                   0
powertrain             0
year                   0
unit               22582
value                  0
Aggregate group        0
dtype: int64
Duplicate rows: 15

In [8]:
# PART 8: Investigate rows with missing region or unit

print("Rows with missing region:")
display(df[df["region_country"].isna()].head(10))

print("\nRows with missing unit:")
display(df[df["unit"].isna()].head(10))

Rows with missing region:

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
20772,NaN,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,4900.0,Other
20773,NaN,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,8500.0,Other
20774,NaN,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2010,NaN,26000.0,Other
20775,NaN,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,4900.0,Other
20776,NaN,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,7200.0,Other
20854,NaN,Historical,price_p0_2025USD,City car,BEV,2011,NaN,45000.0,Other
20855,NaN,Historical,price_p0_2025USD,City car,ICEV,2011,NaN,4800.0,Other
20856,NaN,Historical,price_p0_2025USD,Large car,ICEV,2011,NaN,22000.0,Other
20857,NaN,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2011,NaN,26000.0,Other
20858,NaN,Historical,price_p0_2025USD,Medium car,ICEV,2011,NaN,4800.0,Other

Rows with missing unit:

,region_country,category,parameter,mode,powertrain,year,unit,value,Aggregate group
20719,Australia,Historical,price_p0_2025USD,City car,BEV,2010,NaN,41000.0,Other
20720,Australia,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,11000.0,Other
20721,Australia,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,29000.0,Other
20722,Australia,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,11000.0,Other
20723,Australia,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,19000.0,Other
20724,Brazil,Historical,price_p0_2025USD,City car,ICEV,2010,NaN,9600.0,Other
20725,Brazil,Historical,price_p0_2025USD,Large car,ICEV,2010,NaN,27000.0,Other
20726,Brazil,Historical,price_p0_2025USD,Large SUV/Pick-up,ICEV,2010,NaN,56000.0,Other
20727,Brazil,Historical,price_p0_2025USD,Medium car,ICEV,2010,NaN,11000.0,Other
20728,Brazil,Historical,price_p0_2025USD,Small SUV/Pick-up,ICEV,2010,NaN,21000.0,Other

In [9]:
# PART 9: Check duplicate rows

duplicates = df[df.duplicated(keep=False)]

print(duplicates)

             region_country    category                         parameter  \
19170  United Arab Emirates  Historical  Electric LDVs per charging point
19210  United Arab Emirates  Historical  Electric LDVs per charging point
19250  United Arab Emirates  Historical  Electric LDVs per charging point
19290  United Arab Emirates  Historical  Electric LDVs per charging point
19330  United Arab Emirates  Historical  Electric LDVs per charging point
19352  United Arab Emirates  Historical  Electric LDVs per charging point
19355  United Arab Emirates  Historical  Electric LDVs per charging point
19359  United Arab Emirates  Historical  Electric LDVs per charging point
19363  United Arab Emirates  Historical  Electric LDVs per charging point
19367  United Arab Emirates  Historical  Electric LDVs per charging point
19623  United Arab Emirates  Historical           Average capacity per EV
19663  United Arab Emirates  Historical           Average capacity per EV
19703  United Arab Emirates  Historical           Average capacity per EV
19743  United Arab Emirates  Historical           Average capacity per EV
19783  United Arab Emirates  Historical           Average capacity per EV
19805  United Arab Emirates  Historical           Average capacity per EV
19808  United Arab Emirates  Historical           Average capacity per EV
19812  United Arab Emirates  Historical           Average capacity per EV
19816  United Arab Emirates  Historical           Average capacity per EV
19820  United Arab Emirates  Historical           Average capacity per EV
20077  United Arab Emirates  Historical         Average capacity per EVSE
20117  United Arab Emirates  Historical         Average capacity per EVSE
20157  United Arab Emirates  Historical         Average capacity per EVSE
20197  United Arab Emirates  Historical         Average capacity per EVSE
20237  United Arab Emirates  Historical         Average capacity per EVSE
20259  United Arab Emirates  Historical         Average capacity per EVSE
20262  United Arab Emirates  Historical         Average capacity per EVSE
20266  United Arab Emirates  Historical         Average capacity per EVSE
20270  United Arab Emirates  Historical         Average capacity per EVSE
20274  United Arab Emirates  Historical         Average capacity per EVSE

      mode powertrain  year      unit    value Aggregate group
19170   EV         EV  2021  vehicles   49.000           Other
19210   EV         EV  2022  vehicles  120.000           Other
19250   EV         EV  2023  vehicles  220.000           Other
19290   EV         EV  2024  vehicles  280.000           Other
19330   EV         EV  2025  vehicles  160.000           Other
19352   EV         EV  2021  vehicles   49.000           Other
19355   EV         EV  2022  vehicles  120.000           Other
19359   EV         EV  2023  vehicles  220.000           Other
19363   EV         EV  2024  vehicles  280.000           Other
19367   EV         EV  2025  vehicles  160.000           Other
19623   EV         EV  2021     kW/EV    0.310           Other
19663   EV         EV  2022     kW/EV    0.120           Other
19703   EV         EV  2023     kW/EV    0.069           Other
19743   EV         EV  2024     kW/EV    0.054           Other
19783   EV         EV  2025     kW/EV    0.096           Other
19805   EV         EV  2021     kW/EV    0.310           Other
19808   EV         EV  2022     kW/EV    0.120           Other
19812   EV         EV  2023     kW/EV    0.069           Other
19816   EV         EV  2024     kW/EV    0.054           Other
19820   EV         EV  2025     kW/EV    0.096           Other
20077   EV         EV  2021   kW/EVSE   15.000           Other
20117   EV         EV  2022   kW/EVSE   15.000           Other
20157   EV         EV  2023   kW/EVSE   15.000           Other
20197   EV         EV  2024   kW/EVSE   15.000           Other
20237   EV         EV  2025   kW/EVSE   15.000           Other
20259   EV         EV  2021   kW/EVSE   15.000           Other
20262   EV         EV  2022   kW/EVSE   15.000           Other
20266   EV         EV  2023   kW/EVSE   15.000           Other
20270   EV         EV  2024   kW/EVSE   15.000           Other
20274   EV         EV  2025   kW/EVSE   15.000           Other

In [10]:
# PART 10: Check available EV parameters

parameters = df["parameter"].value_counts()

print(parameters)

parameter
EV stock                            7891
EV sales                            7647
price_p0_2025USD                    3226
price_p100_2025USD                  3226
price_p25_2025USD                   3226
price_p50_2025USD                   3226
price_p75_2025USD                   3226
price_p95_2025USD                   3226
price_mean_2025USD                  3226
EV sales share                      2833
EV stock share                      2777
EV charging points                  1457
Oil displacement Mlge                622
Oil displacement, Mbd                622
Average capacity per EVSE            602
Electric LDVs per charging point     601
Average capacity per EV              601
Electricity demand                   594
Battery deployment                   546
Name: count, dtype: int64

In [11]:
# PART 11: Check available categories

print(df["category"].value_counts())

category
Historical          48114
Projection-STEPS      640
Projection-CPS        621
Name: count, dtype: int64

In [12]:
# PART 12: Check available vehicle modes

print(df["mode"].value_counts())

mode
Cars                 7941
All cars             5964
2 and 3 wheelers     4633
Vans                 4375
Buses                3993
Medium car           3780
Large car            3465
Small SUV/Pick-up    3325
City car             3073
Large SUV/Pick-up    2975
Trucks               2590
EV                   1804
EVSE                 1457
Name: count, dtype: int64

In [13]:
# PART 13: Check available countries and regions

print("Total unique regions/countries:",df["region_country"].nunique())

print("\nCountries/regions:")
print(df["region_country"].dropna().unique())

Total unique regions/countries: 72

Countries/regions:
<ArrowStringArray>
[                           'Chile',                           'Norway',
                         'Portugal',                           'Canada',
                           'France',                          'Germany',
                            'Italy',                      'Netherlands',
                      'Switzerland',                          'Belgium',
                          'Denmark',                          'Finland',
                            'Spain',                   'United Kingdom',
                           'Greece',                          'Iceland',
                           'Poland',                           'Sweden',
                        'Australia',                           'Mexico',
                      'New Zealand',                     'South Africa',
                         'Thailand',                           'Brazil',
                         'Malaysia',                          'Austria',
                          'Turkiye',                         'Colombia',
                        'Indonesia',                           'Israel',
                           'Jordan',                           'Russia',
                         'Viet Nam',                       'Costa Rica',
                      'Philippines',                        'Singapore',
             'United Arab Emirates',                          'Uruguay',
                         'Cambodia',                          'Lao PDR',
                       'Uzbekistan',                            'World',
                            'China',                           'Europe',
                            'India',                    'Latin America',
                            'Japan',                            'Korea',
                   'Southeast Asia',                              'USA',
               'Advanced Economies', 'Developing Economies excl. China',
                           'Africa',                     'Asia Pacific',
                   'European Union',          'Middle East and Caspian',
                         'Bulgaria',                          'Croatia',
                           'Cyprus',                   'Czech Republic',
                          'Estonia',                          'Hungary',
                          'Ireland',                           'Latvia',
                        'Lithuania',                       'Luxembourg',
                            'Nepal',                          'Romania',
                       'Seychelles',                         'Slovakia',
                         'Slovenia',                        'Argentina']
Length: 72, dtype: str

In [14]:
# PART 14: Check powertrain types

print(df["powertrain"].value_counts())

powertrain
EV                               15416
BEV                              11584
ICEV                              9268
PHEV                              7773
FCEV                              1623
ALL                               1568
EREV                               686
Publicly available slow            580
Publicly available fast            546
Publicly available ultra-fast      331
Name: count, dtype: int64

In [15]:
# PART 15: Select relevant parameters for the EV market project

selected_parameters = [
    "EV sales",
    "EV stock",
    "EV sales share",
    "EV stock share",
    "EV charging points",
    "Electric LDVs per charging point",
    "Battery deployment"
]

df_clean = df[df["parameter"].isin(selected_parameters)].copy()

print("Rows after parameter selection:",df_clean.shape[0])
print("Columns:",df_clean.shape[1])

Rows after parameter selection: 23752
Columns: 9

In [16]:
# PART 16: Remove exact duplicate rows

df_clean = df_clean.drop_duplicates()

print("Rows after removing duplicates:",df_clean.shape[0])

Rows after removing duplicates: 23747

In [17]:
# PART 17: Remove rows with missing region or country

df_clean = df_clean.dropna(subset=["region_country"])

print("Rows after removing missing regions:",df_clean.shape[0])

Rows after removing missing regions: 23747

In [18]:
# PART 18: Check cleaned dataset

print(df_clean.info())

print("\nMissing values:")
print(df_clean.isnull().sum())

<class 'pandas.DataFrame'>
Index: 23747 entries, 0 to 49374
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   region_country   23747 non-null  str
 1   category         23747 non-null  str
 2   parameter        23747 non-null  str
 3   mode             23747 non-null  str
 4   powertrain       23747 non-null  str
 5   year             23747 non-null  int64
 6   unit             23747 non-null  str
 7   value            23747 non-null  float64
 8   Aggregate group  23747 non-null  str
dtypes: float64(1), int64(1), str(7)
memory usage: 3.1 MB
None

Missing values:
region_country     0
category           0
parameter          0
mode               0
powertrain         0
year               0
unit               0
value              0
Aggregate group    0
dtype: int64

In [19]:
# PART 19: Check units for each parameter

print(df_clean.groupby("parameter")["unit"].unique())

parameter
Battery deployment                              [GWh]
EV charging points                  [charging points]
EV sales                                   [Vehicles]
EV sales share                              [percent]
EV stock                                   [Vehicles]
EV stock share                              [percent]
Electric LDVs per charging point           [vehicles]
Name: unit, dtype: object

In [20]:
# PART 20: Check parameter and category combinations

print(df_clean.groupby(["parameter","category"]).size())

parameter                         category
Battery deployment                Historical           456
                                  Projection-CPS        45
                                  Projection-STEPS      45
EV charging points                Historical          1403
                                  Projection-CPS        27
                                  Projection-STEPS      27
EV sales                          Historical          7346
                                  Projection-CPS       145
                                  Projection-STEPS     156
EV sales share                    Historical          2743
                                  Projection-CPS        45
                                  Projection-STEPS      45
EV stock                          Historical          7579
                                  Projection-CPS       152
                                  Projection-STEPS     160
EV stock share                    Historical          2687
                                  Projection-CPS        45
                                  Projection-STEPS      45
Electric LDVs per charging point  Historical           578
                                  Projection-CPS         9
                                  Projection-STEPS       9
dtype: int64

In [21]:
# PART 21: Save the cleaned project dataset

cleaned_file_path = "../data/EV_market_cleaned.csv"

df_clean.to_csv(cleaned_file_path,index=False)

print("Cleaned dataset saved successfully")
print("Location:",cleaned_file_path)

Cleaned dataset saved successfully
Location: ../data/EV_market_cleaned.csv

In [22]:
# PART 23: Inspect EV sales by mode and powertrain

ev_sales = df_clean[
    (df_clean["parameter"] == "EV sales") &
    (df_clean["category"] == "Historical")
].copy()

print("EV sales rows:",ev_sales.shape[0])

print("\nModes:")
print(ev_sales["mode"].value_counts())

print("\nPowertrains:")
print(ev_sales["powertrain"].value_counts())

EV sales rows: 7346

Modes:
mode
Cars                2949
2 and 3 wheelers    1328
Vans                1281
Buses               1097
Trucks               691
Name: count, dtype: int64

Powertrains:
powertrain
EV      2750
BEV     2738
PHEV    1244
FCEV     614
Name: count, dtype: int64

In [23]:
# PART 24: Inspect EV sales records for the World

world_sales = ev_sales[ev_sales["region_country"] == "World"]

print(world_sales[["mode","powertrain","year","unit","value"]].head(30))

                  mode powertrain  year      unit       value
6496  2 and 3 wheelers        BEV  2010  Vehicles     41000.0
6497  2 and 3 wheelers        BEV  2011  Vehicles     31000.0
6498  2 and 3 wheelers        BEV  2012  Vehicles   2000000.0
6499  2 and 3 wheelers        BEV  2013  Vehicles   2300000.0
6500  2 and 3 wheelers        BEV  2014  Vehicles   2800000.0
6501  2 and 3 wheelers        BEV  2015  Vehicles   2800000.0
6502  2 and 3 wheelers        BEV  2016  Vehicles   3100000.0
6503  2 and 3 wheelers        BEV  2017  Vehicles   3600000.0
6504  2 and 3 wheelers        BEV  2018  Vehicles   5100000.0
6505  2 and 3 wheelers        BEV  2019  Vehicles   6600000.0
6506  2 and 3 wheelers        BEV  2020  Vehicles   8800000.0
6507  2 and 3 wheelers        BEV  2021  Vehicles  11000000.0
6508  2 and 3 wheelers        BEV  2022  Vehicles   9700000.0
6509  2 and 3 wheelers        BEV  2023  Vehicles  10000000.0
6510  2 and 3 wheelers        BEV  2024  Vehicles   9500000.0
6511  2 and 3 wheelers        BEV  2025  Vehicles  11000000.0
6512             Buses        BEV  2010  Vehicles      1100.0
6513             Buses        BEV  2011  Vehicles       490.0
6514             Buses        BEV  2012  Vehicles      1600.0
6515             Buses        BEV  2013  Vehicles      2200.0
6516             Buses        BEV  2014  Vehicles      4300.0
6517             Buses        BEV  2015  Vehicles     44000.0
6518             Buses        BEV  2016  Vehicles     77000.0
6519             Buses        BEV  2017  Vehicles     89000.0
6520             Buses        BEV  2018  Vehicles     85000.0
6521             Buses        BEV  2019  Vehicles     72000.0
6522             Buses        BEV  2020  Vehicles     58000.0
6523             Buses        BEV  2021  Vehicles     49000.0
6524             Buses        BEV  2022  Vehicles     57000.0
6525             Buses        BEV  2023  Vehicles     44000.0

In [24]:
# PART 25: Inspect all World EV sales records

world_sales = ev_sales[ev_sales["region_country"] == "World"]

print(world_sales[["mode","powertrain","year","value"]].to_string(index=False))

            mode powertrain  year      value
2 and 3 wheelers        BEV  2010    41000.0
2 and 3 wheelers        BEV  2011    31000.0
2 and 3 wheelers        BEV  2012  2000000.0
2 and 3 wheelers        BEV  2013  2300000.0
2 and 3 wheelers        BEV  2014  2800000.0
2 and 3 wheelers        BEV  2015  2800000.0
2 and 3 wheelers        BEV  2016  3100000.0
2 and 3 wheelers        BEV  2017  3600000.0
2 and 3 wheelers        BEV  2018  5100000.0
2 and 3 wheelers        BEV  2019  6600000.0
2 and 3 wheelers        BEV  2020  8800000.0
2 and 3 wheelers        BEV  2021 11000000.0
2 and 3 wheelers        BEV  2022  9700000.0
2 and 3 wheelers        BEV  2023 10000000.0
2 and 3 wheelers        BEV  2024  9500000.0
2 and 3 wheelers        BEV  2025 11000000.0
           Buses        BEV  2010     1100.0
           Buses        BEV  2011      490.0
           Buses        BEV  2012     1600.0
           Buses        BEV  2013     2200.0
           Buses        BEV  2014     4300.0
           Buses        BEV  2015    44000.0
           Buses        BEV  2016    77000.0
           Buses        BEV  2017    89000.0
           Buses        BEV  2018    85000.0
           Buses        BEV  2019    72000.0
           Buses        BEV  2020    58000.0
           Buses        BEV  2021    49000.0
           Buses        BEV  2022    57000.0
           Buses        BEV  2023    44000.0
           Buses        BEV  2024    61000.0
           Buses        BEV  2025    68000.0
           Buses       FCEV  2016       52.0
           Buses       FCEV  2017      390.0
           Buses       FCEV  2018      910.0
           Buses       FCEV  2019     1100.0
           Buses       FCEV  2020     1500.0
           Buses       FCEV  2021     1000.0
           Buses       FCEV  2022     1800.0
           Buses       FCEV  2023     1900.0
           Buses       FCEV  2024     2000.0
           Buses       FCEV  2025     2000.0
           Buses       PHEV  2011      160.0
           Buses       PHEV  2012      510.0
           Buses       PHEV  2013     1800.0
           Buses       PHEV  2014     6000.0
           Buses       PHEV  2015    14000.0
           Buses       PHEV  2016     7900.0
           Buses       PHEV  2017      290.0
           Buses       PHEV  2018     1300.0
           Buses       PHEV  2019     1400.0
           Buses       PHEV  2020     2000.0
           Buses       PHEV  2021     1000.0
           Buses       PHEV  2022     1200.0
           Buses       PHEV  2023     1500.0
           Buses       PHEV  2024     1500.0
           Buses       PHEV  2025     1300.0
            Cars        BEV  2010     7000.0
            Cars        BEV  2011    40000.0
            Cars        BEV  2012    59000.0
            Cars        BEV  2013   110000.0
            Cars        BEV  2014   200000.0
            Cars        BEV  2015   330000.0
            Cars        BEV  2016   470000.0
            Cars        BEV  2017   760000.0
            Cars        BEV  2018  1400000.0
            Cars        BEV  2019  1500000.0
            Cars        BEV  2020  2000000.0
            Cars        BEV  2021  4700000.0
            Cars        BEV  2022  7300000.0
            Cars        BEV  2023  9500000.0
            Cars        BEV  2024 11000000.0
            Cars        BEV  2025 14000000.0
            Cars       FCEV  2010       13.0
            Cars       FCEV  2012        1.0
            Cars       FCEV  2013       23.0
            Cars       FCEV  2014       89.0
            Cars       FCEV  2015      720.0
            Cars       FCEV  2016     2400.0
            Cars       FCEV  2017     3500.0
            Cars       FCEV  2018     4500.0
            Cars       FCEV  2019     7500.0
            Cars       FCEV  2020     7600.0
            Cars       FCEV  2021    16000.0
            Cars       FCEV  2022    15000.0
            Cars       FCEV  2023     9000.0
            Cars       FCEV  2024     5300.0
            Cars       FCEV  2025     7300.0
            Cars       PHEV  2010      450.0
            Cars       PHEV  2011     9000.0
            Cars       PHEV  2012    60000.0
            Cars       PHEV  2013    91000.0
            Cars       PHEV  2014   130000.0
            Cars       PHEV  2015   190000.0
            Cars       PHEV  2016   310000.0
            Cars       PHEV  2017   440000.0
            Cars       PHEV  2018   650000.0
            Cars       PHEV  2019   580000.0
            Cars       PHEV  2020   980000.0
            Cars       PHEV  2021  1900000.0
            Cars       PHEV  2022  2900000.0
            Cars       PHEV  2023  4200000.0
            Cars       PHEV  2024  6500000.0
            Cars       PHEV  2025  7200000.0
          Trucks        BEV  2010       37.0
          Trucks        BEV  2011      200.0
          Trucks        BEV  2012       28.0
          Trucks        BEV  2013       40.0
          Trucks        BEV  2014       55.0
          Trucks        BEV  2015    17000.0
          Trucks        BEV  2016    47000.0
          Trucks        BEV  2017    71000.0
          Trucks        BEV  2018    37000.0
          Trucks        BEV  2019    25000.0
          Trucks        BEV  2020    16000.0
          Trucks        BEV  2021    34000.0
          Trucks        BEV  2022    68000.0
          Trucks        BEV  2023    98000.0
          Trucks        BEV  2024   200000.0
          Trucks        BEV  2025   430000.0
          Trucks       FCEV  2018      400.0
          Trucks       FCEV  2019     2000.0
          Trucks       FCEV  2020     1400.0
          Trucks       FCEV  2021     1200.0
          Trucks       FCEV  2022     2800.0
          Trucks       FCEV  2023     3900.0
          Trucks       FCEV  2024     4800.0
          Trucks       FCEV  2025     7400.0
          Trucks       PHEV  2015       13.0
          Trucks       PHEV  2016        3.0
          Trucks       PHEV  2017        4.0
          Trucks       PHEV  2018        4.0
          Trucks       PHEV  2019       35.0
          Trucks       PHEV  2020      360.0
          Trucks       PHEV  2021     1400.0
          Trucks       PHEV  2022     1500.0
          Trucks       PHEV  2023     3700.0
          Trucks       PHEV  2024     9200.0
          Trucks       PHEV  2025    13000.0
            Vans        BEV  2010     1100.0
            Vans        BEV  2011     3200.0
            Vans        BEV  2012    11000.0
            Vans        BEV  2013    11000.0
            Vans        BEV  2014    11000.0
            Vans        BEV  2015    13000.0
            Vans        BEV  2016    15000.0
            Vans        BEV  2017    20000.0
            Vans        BEV  2018    28000.0
            Vans        BEV  2019    35000.0
            Vans        BEV  2020    59000.0
            Vans        BEV  2021   110000.0
            Vans        BEV  2022   180000.0
            Vans        BEV  2023   260000.0
            Vans        BEV  2024   280000.0
            Vans        BEV  2025   370000.0
            Vans       FCEV  2010        2.0
            Vans       FCEV  2013       50.0
            Vans       FCEV  2014       85.0
            Vans       FCEV  2015      140.0
            Vans       FCEV  2016       99.0
            Vans       FCEV  2017       26.0
            Vans       FCEV  2018       96.0
            Vans       FCEV  2019       15.0
            Vans       FCEV  2020       76.0
            Vans       FCEV  2021      110.0
            Vans       FCEV  2022      830.0
            Vans       FCEV  2023     2000.0
            Vans       FCEV  2024     2600.0
            Vans       FCEV  2025       12.0
            Vans       PHEV  2012       11.0
            Vans       PHEV  2013        5.0
            Vans       PHEV  2014       20.0
            Vans       PHEV  2015      780.0
            Vans       PHEV  2016      170.0
            Vans       PHEV  2017      140.0
            Vans       PHEV  2018      190.0
            Vans       PHEV  2019      280.0
            Vans       PHEV  2020     2600.0
            Vans       PHEV  2021     9200.0
            Vans       PHEV  2022     8300.0
            Vans       PHEV  2023     8800.0
            Vans       PHEV  2024    18000.0
            Vans       PHEV  2025    62000.0
2 and 3 wheelers         EV  2010    41000.0
2 and 3 wheelers         EV  2011    31000.0
2 and 3 wheelers         EV  2012  2000000.0
2 and 3 wheelers         EV  2013  2300000.0
2 and 3 wheelers         EV  2014  2800000.0
2 and 3 wheelers         EV  2015  2800000.0
2 and 3 wheelers         EV  2016  3100000.0
2 and 3 wheelers         EV  2017  3600000.0
2 and 3 wheelers         EV  2018  5100000.0
2 and 3 wheelers         EV  2019  6600000.0
2 and 3 wheelers         EV  2020  8800000.0
2 and 3 wheelers         EV  2021 11000000.0
2 and 3 wheelers         EV  2022  9700000.0
2 and 3 wheelers         EV  2023 10000000.0
2 and 3 wheelers         EV  2024  9500000.0
2 and 3 wheelers         EV  2025 11000000.0
           Buses         EV  2010     1100.0
           Buses         EV  2011      650.0
           Buses         EV  2012     2100.0
           Buses         EV  2013     4000.0
           Buses         EV  2014    10000.0
           Buses         EV  2015    57000.0
           Buses         EV  2016    85000.0
           Buses         EV  2017    89000.0
           Buses         EV  2018    86000.0
           Buses         EV  2019    74000.0
           Buses         EV  2020    60000.0
           Buses         EV  2021    50000.0
           Buses         EV  2022    58000.0
           Buses         EV  2023    46000.0
           Buses         EV  2024    62000.0
           Buses         EV  2025    70000.0
            Cars         EV  2010     7400.0
            Cars         EV  2011    49000.0
            Cars         EV  2012   120000.0
            Cars         EV  2013   210000.0
            Cars         EV  2014   330000.0
            Cars         EV  2015   530000.0
            Cars         EV  2016   780000.0
            Cars         EV  2017  1200000.0
            Cars         EV  2018  2000000.0
            Cars         EV  2019  2100000.0
            Cars         EV  2020  3000000.0
            Cars         EV  2021  6600000.0
            Cars         EV  2022 10000000.0
            Cars         EV  2023 14000000.0
            Cars         EV  2024 17000000.0
            Cars         EV  2025 21000000.0
          Trucks         EV  2010       37.0
          Trucks         EV  2011      200.0
          Trucks         EV  2012       28.0
          Trucks         EV  2013       40.0
          Trucks         EV  2014       55.0
          Trucks         EV  2015    17000.0
          Trucks         EV  2016    47000.0
          Trucks         EV  2017    71000.0
          Trucks         EV  2018    37000.0
          Trucks         EV  2019    25000.0
          Trucks         EV  2020    16000.0
          Trucks         EV  2021    36000.0
          Trucks         EV  2022    70000.0
          Trucks         EV  2023   100000.0
          Trucks         EV  2024   210000.0
          Trucks         EV  2025   440000.0
            Vans         EV  2010     1100.0
            Vans         EV  2011     3200.0
            Vans         EV  2012    11000.0
            Vans         EV  2013    11000.0
            Vans         EV  2014    11000.0
            Vans         EV  2015    14000.0
            Vans         EV  2016    15000.0
            Vans         EV  2017    20000.0
            Vans         EV  2018    28000.0
            Vans         EV  2019    35000.0
            Vans         EV  2020    62000.0
            Vans         EV  2021   120000.0
            Vans         EV  2022   190000.0
            Vans         EV  2023   270000.0
            Vans         EV  2024   300000.0
            Vans         EV  2025   430000.0

In [25]:
# PART 26: Check unique World EV sales combinations

print(
    world_sales[["mode","powertrain"]]
    .drop_duplicates()
    .sort_values(["mode","powertrain"])
    .to_string(index=False)
)

            mode powertrain
2 and 3 wheelers        BEV
2 and 3 wheelers         EV
           Buses        BEV
           Buses         EV
           Buses       FCEV
           Buses       PHEV
            Cars        BEV
            Cars         EV
            Cars       FCEV
            Cars       PHEV
          Trucks        BEV
          Trucks         EV
          Trucks       FCEV
          Trucks       PHEV
            Vans        BEV
            Vans         EV
            Vans       FCEV
            Vans       PHEV

In [26]:
# PART 27: Create historical global EV sales dataset

global_ev_sales = ev_sales[
    (ev_sales["region_country"] == "World") &
    (ev_sales["powertrain"] == "EV")
].copy()

global_ev_sales = (
    global_ev_sales
    .groupby("year",as_index=False)["value"]
    .sum()
    .sort_values("year")
)

print(global_ev_sales)

    year       value
0   2010     50637.0
1   2011     84050.0
2   2012   2133128.0
3   2013   2525040.0
4   2014   3151055.0
5   2015   3418000.0
6   2016   4027000.0
7   2017   4980000.0
8   2018   7251000.0
9   2019   8834000.0
10  2020  11938000.0
11  2021  17806000.0
12  2022  20018000.0
13  2023  24416000.0
14  2024  27072000.0
15  2025  32940000.0

In [27]:
# PART 28: Calculate global EV sales growth

global_ev_sales["growth_rate"] = (
    global_ev_sales["value"].pct_change() * 100
)

print(global_ev_sales)

    year       value  growth_rate
0   2010     50637.0          NaN
1   2011     84050.0    65.985347
2   2012   2133128.0  2437.927424
3   2013   2525040.0    18.372643
4   2014   3151055.0    24.792281
5   2015   3418000.0     8.471607
6   2016   4027000.0    17.817437
7   2017   4980000.0    23.665259
8   2018   7251000.0    45.602410
9   2019   8834000.0    21.831472
10  2020  11938000.0    35.136971
11  2021  17806000.0    49.153962
12  2022  20018000.0    12.422779
13  2023  24416000.0    21.970227
14  2024  27072000.0    10.878113
15  2025  32940000.0    21.675532

In [30]:
# PART 29: Create interactive global EV sales trend

import plotly.express as px

fig = px.line(
    global_ev_sales,
    x="year",
    y="value",
    markers=True,
    title="Global EV Sales Trend (2010–2025)",
    labels={
        "year":"Year",
        "value":"EV Sales (Vehicles)"
    }
)

fig.update_layout(
    width=1200,
    height=600,
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    title_font=dict(color="white",size=22),
    xaxis=dict(
        title="Year",
        color="white",
        gridcolor="gray"
    ),
    yaxis=dict(
        title="EV Sales (Vehicles)",
        color="white",
        gridcolor="gray"
    ),
    hovermode="x unified"
)

fig.show()

In [31]:
# PART 30: Check aggregate groups

print(df_clean["Aggregate group"].value_counts())

Aggregate group
Other                 14048
Projection_country     3100
Other_aggregate        2728
Projection_region      2204
_World                  928
European Union          739
Name: count, dtype: int64

In [32]:
# PART 31: Check 2025 EV sales by aggregate group

sales_2025 = ev_sales[
    (ev_sales["year"] == 2025) &
    (ev_sales["powertrain"] == "EV")
].copy()

print(
    sales_2025.groupby("Aggregate group")["value"]
    .sum()
    .sort_values(ascending=False)
)

Aggregate group
Other_aggregate       37632132.0
_World                32940000.0
Projection_country    25156800.0
Other                  6923092.0
Projection_region      6505040.0
European Union         3152700.0
Name: value, dtype: float64

In [33]:
# PART 32: Check country and aggregate-group mapping

country_groups = (
    sales_2025[["region_country","Aggregate group"]]
    .drop_duplicates()
    .sort_values("region_country")
)

print(country_groups.to_string(index=False))

                  region_country    Aggregate group
              Advanced Economies    Other_aggregate
                          Africa    Other_aggregate
                    Asia Pacific    Other_aggregate
                       Australia              Other
                         Austria              Other
                         Belgium              Other
                          Brazil              Other
                        Bulgaria              Other
                        Cambodia              Other
                          Canada              Other
                           Chile              Other
                           China Projection_country
                        Colombia              Other
                      Costa Rica              Other
                         Croatia              Other
                          Cyprus              Other
                  Czech Republic              Other
                         Denmark              Other
Developing Economies excl. China    Other_aggregate
                         Estonia              Other
                          Europe  Projection_region
                  European Union     European Union
                         Finland              Other
                          France              Other
                         Germany              Other
                          Greece              Other
                         Hungary              Other
                         Iceland              Other
                           India Projection_country
                       Indonesia              Other
                         Ireland              Other
                          Israel              Other
                           Italy              Other
                           Japan Projection_country
                          Jordan              Other
                           Korea Projection_country
                         Lao PDR              Other
                   Latin America  Projection_region
                          Latvia              Other
                       Lithuania              Other
                      Luxembourg              Other
                        Malaysia              Other
                          Mexico              Other
         Middle East and Caspian    Other_aggregate
                           Nepal              Other
                     Netherlands              Other
                     New Zealand              Other
                          Norway              Other
                     Philippines              Other
                          Poland              Other
                        Portugal              Other
                         Romania              Other
                          Russia              Other
                       Singapore              Other
                        Slovakia              Other
                        Slovenia              Other
                    South Africa              Other
                  Southeast Asia  Projection_region
                           Spain              Other
                          Sweden              Other
                     Switzerland              Other
                        Thailand              Other
                         Turkiye              Other
                             USA Projection_country
            United Arab Emirates              Other
                  United Kingdom              Other
                         Uruguay              Other
                      Uzbekistan              Other
                        Viet Nam              Other
                           World             _World

In [34]:
# PART 33: Create country-level EV sales dataset

country_sales = sales_2025[
    sales_2025["Aggregate group"].isin(["Other","Projection_country"])
].copy()

print("Number of countries:",country_sales["region_country"].nunique())

print("\nCountries:")
print(country_sales["region_country"].unique())

Number of countries: 60

Countries:
<ArrowStringArray>
[           'Australia',              'Austria',              'Belgium',
               'Brazil',             'Bulgaria',             'Cambodia',
               'Canada',                'Chile',                'China',
             'Colombia',           'Costa Rica',              'Croatia',
               'Cyprus',       'Czech Republic',              'Denmark',
              'Estonia',              'Finland',               'France',
              'Germany',               'Greece',              'Hungary',
              'Iceland',                'India',            'Indonesia',
              'Ireland',               'Israel',                'Italy',
                'Japan',               'Jordan',                'Korea',
              'Lao PDR',               'Latvia',            'Lithuania',
           'Luxembourg',             'Malaysia',               'Mexico',
                'Nepal',          'Netherlands',          'New Zealand',
               'Norway',          'Philippines',               'Poland',
             'Portugal',              'Romania',               'Russia',
            'Singapore',             'Slovakia',             'Slovenia',
         'South Africa',                'Spain',               'Sweden',
          'Switzerland',             'Thailand',              'Turkiye',
                  'USA', 'United Arab Emirates',       'United Kingdom',
              'Uruguay',           'Uzbekistan',             'Viet Nam']
Length: 60, dtype: str

In [35]:
# PART 34: Calculate 2025 EV sales by country

country_sales_2025 = (
    country_sales
    .groupby("region_country",as_index=False)["value"]
    .sum()
    .sort_values("value",ascending=False)
)

print(country_sales_2025.head(15).to_string(index=False))

region_country      value
         China 20980000.0
         India  2283500.0
           USA  1515900.0
      Viet Nam   920110.0
       Germany   906200.0
United Kingdom   746500.0
        France   503610.0
       Turkiye   410000.0
   Netherlands   260190.0
         Spain   251680.0
         Korea   245700.0
         Italy   207800.0
     Indonesia   197000.0
        Canada   191440.0
        Brazil   190400.0

In [36]:
# PART 35: Visualize top 10 EV markets in 2025

top_10_countries = country_sales_2025.head(10)

fig = px.bar(
    top_10_countries,
    x="value",
    y="region_country",
    orientation="h",
    title="Top 10 EV Markets by Sales in 2025",
    labels={
        "value":"EV Sales (Vehicles)",
        "region_country":"Country"
    }
)

fig.update_layout(
    width=1200,
    height=600,
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    title_font=dict(color="white",size=22),
    xaxis=dict(
        title="EV Sales (Vehicles)",
        color="white",
        gridcolor="gray"
    ),
    yaxis=dict(
        title="Country",
        color="white",
        gridcolor="gray"
    )
)

fig.show()

In [37]:
# PART 36: Create major EV market comparison dataset

major_markets = ["China","USA","India","Europe"]

major_market_sales = ev_sales[
    (ev_sales["region_country"].isin(major_markets)) &
    (ev_sales["powertrain"] == "EV")
].copy()

major_market_sales = (
    major_market_sales
    .groupby(["region_country","year"],as_index=False)["value"]
    .sum()
)

print(major_market_sales.head(20))

   region_country  year       value
0           China  2010      2490.0
1           China  2011      5850.0
2           China  2012   1712470.0
3           China  2013   2020470.0
4           China  2014   2484480.0
5           China  2015   2984300.0
6           China  2016   3271000.0
7           China  2017   3941800.0
8           China  2018   5723600.0
9           China  2019   6997400.0
10          China  2020   9372000.0
11          China  2021  14389000.0
12          China  2022  14142000.0
13          China  2023  16064000.0
14          China  2024  18019000.0
15          China  2025  20980000.0
16         Europe  2010      3526.0
17         Europe  2011     13536.0
18         Europe  2012     46987.0
19         Europe  2013     74944.0

In [38]:
# PART 37: Convert EV sales to millions

major_market_sales["sales_millions"] = (
    major_market_sales["value"] / 1_000_000
)

print(major_market_sales.head())

  region_country  year      value  sales_millions
0          China  2010     2490.0         0.00249
1          China  2011     5850.0         0.00585
2          China  2012  1712470.0         1.71247
3          China  2013  2020470.0         2.02047
4          China  2014  2484480.0         2.48448

In [39]:
# PART 38: Visualize major EV market growth

fig = px.line(
    major_market_sales,
    x="year",
    y="sales_millions",
    color="region_country",
    markers=True,
    title="EV Sales Growth in Major Markets",
    labels={
        "year":"Year",
        "sales_millions":"EV Sales (Millions)",
        "region_country":"Market"
    }
)

fig.update_layout(
    width=1200,
    height=600,
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    title_font=dict(color="white",size=22),
    xaxis=dict(
        title="Year",
        color="white",
        gridcolor="gray"
    ),
    yaxis=dict(
        title="EV Sales (Millions)",
        color="white",
        gridcolor="gray"
    ),
    legend=dict(
        font=dict(color="white")
    ),
    hovermode="x unified"
)

fig.show()

In [40]:
# PART 39: Create historical EV sales share dataset

ev_sales_share = df_clean[
    (df_clean["parameter"] == "EV sales share") &
    (df_clean["category"] == "Historical")
].copy()

print("Rows:",ev_sales_share.shape[0])
print(ev_sales_share[["region_country","mode","powertrain","year","unit","value"]].head(20))

Rows: 2743
           region_country              mode powertrain  year     unit  value
13053  Advanced Economies  2 and 3 wheelers         EV  2010  percent  0.015
13054  Advanced Economies  2 and 3 wheelers         EV  2011  percent  0.012
13055  Advanced Economies  2 and 3 wheelers         EV  2012  percent  0.300
13056  Advanced Economies  2 and 3 wheelers         EV  2013  percent  0.240
13057  Advanced Economies  2 and 3 wheelers         EV  2014  percent  0.260
13058  Advanced Economies  2 and 3 wheelers         EV  2015  percent  0.390
13059  Advanced Economies  2 and 3 wheelers         EV  2016  percent  0.540
13060  Advanced Economies  2 and 3 wheelers         EV  2017  percent  0.980
13061  Advanced Economies  2 and 3 wheelers         EV  2018  percent  1.600
13062  Advanced Economies  2 and 3 wheelers         EV  2019  percent  2.200
13063  Advanced Economies  2 and 3 wheelers         EV  2020  percent  2.800
13064  Advanced Economies  2 and 3 wheelers         EV  2021  percent  3.200
13065  Advanced Economies  2 and 3 wheelers         EV  2022  percent  4.300
13066  Advanced Economies  2 and 3 wheelers         EV  2023  percent  4.200
13067  Advanced Economies  2 and 3 wheelers         EV  2024  percent  4.100
13068  Advanced Economies  2 and 3 wheelers         EV  2025  percent  5.000
13085  Advanced Economies             Buses         EV  2010  percent  0.047
13086  Advanced Economies             Buses         EV  2011  percent  0.015
13087  Advanced Economies             Buses         EV  2012  percent  0.019
13088  Advanced Economies             Buses         EV  2013  percent  0.028

In [41]:
# PART 40: Create global EV sales share trend

global_sales_share = ev_sales_share[
    (ev_sales_share["region_country"] == "World") &
    (ev_sales_share["powertrain"] == "EV")
].copy()

global_sales_share = (
    global_sales_share
    .groupby("year",as_index=False)["value"]
    .mean()
    .sort_values("year")
)

print(global_sales_share)

    year      value
0   2010   0.033178
1   2011   0.042800
2   2012   0.804124
3   2013   0.952168
4   2014   1.180240
5   2015   1.916000
6   2016   2.482000
7   2017   2.880000
8   2018   3.384000
9   2019   3.708000
10  2020   5.122000
11  2021   6.712000
12  2022   7.760000
13  2023   8.360000
14  2024   9.460000
15  2025  11.600000

In [42]:
# PART 41: Visualize global EV sales share

fig = px.line(
    global_sales_share,
    x="year",
    y="value",
    markers=True,
    title="Global EV Sales Share (2010–2025)",
    labels={
        "year":"Year",
        "value":"EV Sales Share (%)"
    }
)

fig.update_layout(
    width=1200,
    height=600,
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    title_font=dict(color="white",size=22),
    xaxis=dict(
        title="Year",
        color="white",
        gridcolor="gray"
    ),
    yaxis=dict(
        title="EV Sales Share (%)",
        color="white",
        gridcolor="gray"
    ),
    hovermode="x unified"
)

fig.show()

In [43]:
# PART 42: Inspect global EV sales share by mode and powertrain

global_share_check = ev_sales_share[
    ev_sales_share["region_country"] == "World"
].copy()

print(
    global_share_check[
        ["mode","powertrain","year","unit","value"]
    ].to_string(index=False)
)

            mode powertrain  year    unit    value
2 and 3 wheelers         EV  2010 percent  0.08300
2 and 3 wheelers         EV  2011 percent  0.05900
2 and 3 wheelers         EV  2012 percent  3.60000
2 and 3 wheelers         EV  2013 percent  4.10000
2 and 3 wheelers         EV  2014 percent  4.70000
2 and 3 wheelers         EV  2015 percent  4.80000
2 and 3 wheelers         EV  2016 percent  5.20000
2 and 3 wheelers         EV  2017 percent  5.60000
2 and 3 wheelers         EV  2018 percent  7.80000
2 and 3 wheelers         EV  2019 percent 10.00000
2 and 3 wheelers         EV  2020 percent 15.00000
2 and 3 wheelers         EV  2021 percent 18.00000
2 and 3 wheelers         EV  2022 percent 15.00000
2 and 3 wheelers         EV  2023 percent 15.00000
2 and 3 wheelers         EV  2024 percent 14.00000
2 and 3 wheelers         EV  2025 percent 15.00000
           Buses         EV  2010 percent  0.05600
           Buses         EV  2011 percent  0.04000
           Buses         EV  2012 percent  0.12000
           Buses         EV  2013 percent  0.23000
           Buses         EV  2014 percent  0.63000
           Buses         EV  2015 percent  3.50000
           Buses         EV  2016 percent  5.00000
           Buses         EV  2017 percent  5.70000
           Buses         EV  2018 percent  5.60000
           Buses         EV  2019 percent  5.00000
           Buses         EV  2020 percent  5.20000
           Buses         EV  2021 percent  4.40000
           Buses         EV  2022 percent  5.10000
           Buses         EV  2023 percent  3.90000
           Buses         EV  2024 percent  4.80000
           Buses         EV  2025 percent  5.00000
            Cars         EV  2010 percent  0.01200
            Cars         EV  2011 percent  0.07200
            Cars         EV  2012 percent  0.17000
            Cars         EV  2013 percent  0.29000
            Cars         EV  2014 percent  0.44000
            Cars         EV  2015 percent  0.68000
            Cars         EV  2016 percent  0.95000
            Cars         EV  2017 percent  1.40000
            Cars         EV  2018 percent  2.50000
            Cars         EV  2019 percent  2.70000
            Cars         EV  2020 percent  4.40000
            Cars         EV  2021 percent  9.30000
            Cars         EV  2022 percent 15.00000
            Cars         EV  2023 percent 18.00000
            Cars         EV  2024 percent 21.00000
            Cars         EV  2025 percent 25.00000
          Trucks         EV  2010 percent  0.00089
          Trucks         EV  2011 percent  0.00400
          Trucks         EV  2012 percent  0.00062
          Trucks         EV  2013 percent  0.00084
          Trucks         EV  2014 percent  0.00120
          Trucks         EV  2015 percent  0.44000
          Trucks         EV  2016 percent  1.10000
          Trucks         EV  2017 percent  1.50000
          Trucks         EV  2018 percent  0.73000
          Trucks         EV  2019 percent  0.50000
          Trucks         EV  2020 percent  0.31000
          Trucks         EV  2021 percent  0.66000
          Trucks         EV  2022 percent  1.60000
          Trucks         EV  2023 percent  2.20000
          Trucks         EV  2024 percent  4.50000
          Trucks         EV  2025 percent  9.00000
            Vans         EV  2010 percent  0.01400
            Vans         EV  2011 percent  0.03900
            Vans         EV  2012 percent  0.13000
            Vans         EV  2013 percent  0.14000
            Vans         EV  2014 percent  0.13000
            Vans         EV  2015 percent  0.16000
            Vans         EV  2016 percent  0.16000
            Vans         EV  2017 percent  0.20000
            Vans         EV  2018 percent  0.29000
            Vans         EV  2019 percent  0.34000
            Vans         EV  2020 percent  0.70000
            Vans         EV  2021 percent  1.20000
            Vans         EV  2022 percent  2.10000
            Vans         EV  2023 percent  2.70000
            Vans         EV  2024 percent  3.00000
            Vans         EV  2025 percent  4.00000

In [45]:
# PART 43: Calculate weighted global EV sales share correctly

global_sales = ev_sales[
    (ev_sales["region_country"] == "World") &
    (ev_sales["powertrain"] == "EV")
][["mode","year","value"]].copy()

global_sales = global_sales.rename(columns={"value":"ev_sales"})

global_share = ev_sales_share[
    (ev_sales_share["region_country"] == "World") &
    (ev_sales_share["powertrain"] == "EV")
][["mode","year","value"]].copy()

global_share = global_share.rename(columns={"value":"ev_sales_share"})

global_share = global_share[global_share["ev_sales_share"] > 0]

global_share_data = pd.merge(
    global_sales,
    global_share,
    on=["mode","year"],
    how="inner"
)

global_share_data["total_vehicle_sales"] = (
    global_share_data["ev_sales"] /
    (global_share_data["ev_sales_share"] / 100)
)

global_share_data = (
    global_share_data
    .groupby("year",as_index=False)
    .agg(
        ev_sales=("ev_sales","sum"),
        total_vehicle_sales=("total_vehicle_sales","sum")
    )
)

global_share_data["ev_sales_share"] = (
    global_share_data["ev_sales"] /
    global_share_data["total_vehicle_sales"] * 100
)

print(global_share_data)

    year    ev_sales  total_vehicle_sales  ev_sales_share
0   2010     50637.0         1.250430e+08        0.040496
1   2011     84050.0         1.354281e+08        0.062062
2   2012   2133128.0         1.408715e+08        1.514237
3   2013   2525040.0         1.428695e+08        1.767375
4   2014   3151055.0         1.492066e+08        2.111873
5   2015   3418000.0         1.505167e+08        2.270844
6   2016   4027000.0         1.570684e+08        2.563852
7   2017   4980000.0         1.662947e+08        2.994683
8   2018   7251000.0         1.616440e+08        4.485784
9   2019   8834000.0         1.605519e+08        5.502271
10  2020  11938000.0         1.420208e+08        8.405813
11  2021  17806000.0         1.486698e+08       11.976881
12  2022  20018000.0         1.458932e+08       13.720995
13  2023  24416000.0         1.601694e+08       15.243862
14  2024  27072000.0         1.647679e+08       16.430389
15  2025  32940000.0         1.743722e+08       18.890624

In [46]:
# PART 44: Visualize corrected global EV sales share

fig = px.line(
    global_share_data,
    x="year",
    y="ev_sales_share",
    markers=True,
    title="Global EV Sales Share (2010–2025)",
    labels={
        "year":"Year",
        "ev_sales_share":"EV Sales Share (%)"
    }
)

fig.update_layout(
    width=1200,
    height=600,
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    title_font=dict(color="white",size=22),
    xaxis=dict(
        title="Year",
        color="white",
        gridcolor="gray"
    ),
    yaxis=dict(
        title="EV Sales Share (%)",
        color="white",
        gridcolor="gray"
    ),
    hovermode="x unified"
)

fig.show()

In [47]:
# PART 45: Create historical global EV stock dataset

ev_stock = df_clean[
    (df_clean["parameter"] == "EV stock") &
    (df_clean["category"] == "Historical") &
    (df_clean["region_country"] == "World") &
    (df_clean["powertrain"] == "EV")
].copy()

global_ev_stock = (
    ev_stock
    .groupby("year",as_index=False)["value"]
    .sum()
    .sort_values("year")
)

global_ev_stock["stock_millions"] = (
    global_ev_stock["value"] / 1_000_000
)

print(global_ev_stock)

    year        value  stock_millions
0   2010     104800.0          0.1048
1   2011     213000.0          0.2130
2   2012    2253600.0          2.2536
3   2013    4567400.0          4.5674
4   2014    7508700.0          7.5087
5   2015   10914000.0         10.9140
6   2016   15405000.0         15.4050
7   2017   20850000.0         20.8500
8   2018   27980000.0         27.9800
9   2019   38150000.0         38.1500
10  2020   49200000.0         49.2000
11  2021   65450000.0         65.4500
12  2022   80880000.0         80.8800
13  2023  110890000.0        110.8900
14  2024  136480000.0        136.4800
15  2025  167420000.0        167.4200

In [48]:
# PART 46: Visualize global EV stock growth

fig = px.line(
    global_ev_stock,
    x="year",
    y="stock_millions",
    markers=True,
    title="Global EV Stock Growth (2010–2025)",
    labels={
        "year":"Year",
        "stock_millions":"EV Stock (Millions)"
    }
)

fig.update_layout(
    width=1200,
    height=600,
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    title_font=dict(color="white",size=22),
    xaxis=dict(
        title="Year",
        color="white",
        gridcolor="gray"
    ),
    yaxis=dict(
        title="EV Stock (Millions)",
        color="white",
        gridcolor="gray"
    ),
    hovermode="x unified"
)

fig.show()

In [49]:
# PART 47: Create historical global EV charging points dataset

ev_charging = df_clean[
    (df_clean["parameter"] == "EV charging points") &
    (df_clean["category"] == "Historical") &
    (df_clean["region_country"] == "World")
].copy()

global_charging = (
    ev_charging
    .groupby("year",as_index=False)["value"]
    .sum()
    .sort_values("year")
)

print(global_charging)

    year      value
0   2010     4010.0
1   2011    10830.0
2   2012    30600.0
3   2013    44600.0
4   2014   103028.0
5   2015   175120.0
6   2016   313100.0
7   2017   412900.0
8   2018   548100.0
9   2019   820000.0
10  2020  1012000.0
11  2021  1517000.0
12  2022  2480000.0
13  2023  3790000.0
14  2024  5350000.0
15  2025  6970000.0

In [50]:
# PART 48: Visualize global EV charging infrastructure

fig = px.line(
    global_charging,
    x="year",
    y="value",
    markers=True,
    title="Global EV Charging Infrastructure Growth",
    labels={
        "year":"Year",
        "value":"Charging Points"
    }
)

fig.update_layout(
    width=1200,
    height=600,
    paper_bgcolor="black",
    plot_bgcolor="black",
    font=dict(color="white"),
    title_font=dict(color="white",size=22),
    xaxis=dict(
        title="Year",
        color="white",
        gridcolor="gray"
    ),
    yaxis=dict(
        title="Charging Points",
        color="white",
        gridcolor="gray"
    ),
    hovermode="x unified"
)

fig.show()

In [52]:
# PART 49: Save final cleaned dataset for Power BI

import os

# Create processed folder if it does not exist
processed_path = r"D:\EV_Market_Forecast\data\processed"

os.makedirs(processed_path,exist_ok=True)

# Save cleaned dataset
output_path = os.path.join(processed_path,"ev_clean.csv")

df_clean.to_csv(output_path,index=False)

print("Final dataset saved:",output_path)
print("Rows:",df_clean.shape[0])
print("Columns:",df_clean.shape[1])

Final dataset saved: D:\EV_Market_Forecast\data\processed\ev_clean.csv
Rows: 23747
Columns: 9

In [53]:
# PART 50: Save analysis datasets for Power BI

global_share_data.to_csv(
    os.path.join(processed_path,"global_ev_sales_share.csv"),
    index=False
)

global_ev_stock.to_csv(
    os.path.join(processed_path,"global_ev_stock.csv"),
    index=False
)

global_charging.to_csv(
    os.path.join(processed_path,"global_ev_charging.csv"),
    index=False
)

print("All analysis datasets saved successfully.")

All analysis datasets saved successfully.